apiVersion: apps/v1
kind: Deployment
metadata:
  name: va
  labels:
    app: va-app 
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: va-app 
  strategy:
    type: RollingUpdate 
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels: 
        app: va-app 
    spec: 
      imagePullSecrets:
        - name: dockerhub-credentials
      containers:
        - name: va-container
          image: docker.io/shadowhub/raz:latest
          ports:
            - containerPort: 8000 
          resources: 
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi