apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: va-argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/chizchig/viva.git
    targetRevision: HEAD
    path: k8/app/overlay/dev/
  destination:
    server: https://kubernetes.default.svc
    namespace: eagle
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 